/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author EG
 */
public class Registro1 extends java.awt.Dialog {

    /**
     * Creates new form Registro1
     */
    public Registro1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setLayout(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        idUsername = new javax.swing.JTextField();
        idPassword = new javax.swing.JTextField();
        Acept = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(null);

        jLabel1.setText("Registro");
        add(jLabel1);
        jLabel1.setBounds(180, 50, 60, 16);
        add(idUsername);
        idUsername.setBounds(170, 100, 110, 24);
        add(idPassword);
        idPassword.setBounds(170, 150, 110, 24);

        Acept.setText("Aceptar");
        add(Acept);
        Acept.setBounds(170, 210, 110, 32);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Registro1 dialog = new Registro1(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Acept;
    public javax.swing.JTextField idPassword;
    public javax.swing.JTextField idUsername;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
